# https://github.com/unibas-dmi-hpc/SPH-EXA_mini-app
# --------------------------------------------------
# DD=Dockerfile.ubuntu1804_cuda101_mpich314_sphexa_ci
# VV=sphexa/mpich:ub1804_cuda101_mpi314_sphexa_ci
# docker build -f ./$DD -t $VV --build-arg branchname=master .
# docker push $VV
# docker run --rm $VV
# docker run --rm $VV bash -c "./gnu7/omp.app -s 1 -n 10"
# docker run --rm $VV bash -c "mpirun -np 2 ./gnu7/mpi+omp.app -s 1 -n 20"
# docker run --rm -it $VV bash
# docker run $VV cat /etc/os-release
FROM ethcscs/mpich:ub1804_cuda101_mpi314_osu

# ARG branchname=develop
# ARG reponame=jgphpc/SPH-EXA_mini-app
# # get the branch from the pull request:
# RUN mkdir -p /sph && cd /sph \
#    && wget https://github.com/$reponame/archive/$branchname.zip \
#    && unzip $branchname.zip \
#    && cd SPH-EXA_mini-app-$branchname

# RUN apt update \
#     && apt install -y unzip

# RUN mkdir -p /SPH-EXA_mini-app

# -----------------------------------------------------------------------------
# This COPY not needed as travis will clone the branch:
# COPY SPH-EXA_mini-app /SPH-EXA_mini-app
# $ git clone --depth=50 --branch=travisJG https://github.com/jgphpc/SPH-EXA_mini-app.git jgphpc/SPH-EXA_mini-app
# $ pwd
# /home/travis/build/jgphpc/SPH-EXA_mini-app
# $ ls -la
# drwxrwxr-x 7 travis travis 4096 Oct 21 13:59 .
# drwxrwxr-x 3 travis travis 4096 Oct 21 13:59 ..
# -rw-rw-r-- 1 travis travis 3254 Oct 21 13:59 .clang-format
# -rw-rw-r-- 1 travis travis 1507 Oct 21 13:59 constants.py
# drwxrwxr-x 8 travis travis 4096 Oct 21 13:59 .git
# -rw-rw-r-- 1 travis travis  438 Oct 21 13:59 .gitignore
# -rw-rw-r-- 1 travis travis 1080 Oct 21 13:59 LICENSE
# -rw-rw-r-- 1 travis travis 3567 Oct 21 13:59 Makefile
# -rw-rw-r-- 1 travis travis 2098 Oct 21 13:59 README.md
# drwxrwxr-x 4 travis travis 4096 Oct 21 13:59 scripts
# drwxrwxr-x 3 travis travis 4096 Oct 21 13:59 src
# drwxrwxr-x 2 travis travis 4096 Oct 21 13:59 test
# drwxrwxr-x 2 travis travis 4096 Oct 21 13:59 tools
# -rw-rw-r-- 1 travis travis 1878 Oct 21 13:59 .travis.yml
# -----------------------------------------------------------------------------

# RUN cd /SPH-EXA_mini-app && ls -la
# RUN cd /sph/SPH-EXA_mini-app-$branchname \
# # compile omp with gnu7:
RUN pwd \
    && make omp CXXFLAGS="-std=c++14 -fopenmp -g -DNDEBUG -I. -Isrc" BINDIR=bin/gnu7 CXX=/usr/bin/g++-7 \
# compile omp with gnu8:
    && make omp CXXFLAGS="-std=c++14 -fopenmp -g -DNDEBUG -I. -Isrc" BINDIR=bin/gnu8 CXX=/usr/bin/g++-8 \
# compile omp with gnu9:
    && make omp CXXFLAGS="-std=c++14 -fopenmp -g -DNDEBUG -I. -Isrc" BINDIR=bin/gnu9 CXX=/usr/bin/g++-9 \
# compile mpi+omp with gnu7 (-DUSE_MPI):
    && make mpi+omp CXXFLAGS="-std=c++14 -fopenmp -g -DNDEBUG -I. -Isrc" BINDIR=bin/gnu7 \
    && ls -laR bin

# TRAVIS_REPO_SLUG=jgphpc/SPH-EXA_mini-app
# USER=travis
# PWD=/home/travis/build/jgphpc/SPH-EXA_mini-app
# HOME=/home/travis
# TRAVIS_BUILD_DIR=/home/travis/build/jgphpc/SPH-EXA_mini-app
# TRAVIS_BRANCH=travisJG
# TRAVIS_HOME=/home/travis

# WORKDIR /sph/SPH-EXA_mini-app-$branchname/bin
WORKDIR $TRAVIS_BUILD_DIR/bin
# /home/travis/build/jgphpc/SPH-EXA_mini-app

CMD ["./gnu7/omp.app", "-s", "0", "-n", "10"]
# CMD ["mpirun", "-np", "2", "./mpi+omp.app", "-s", "0", "-n", "10"]
