include:
  # - local: '.gitlab/ubuntu/ubuntu_*.yml'
  - local: '.gitlab/common.yml'
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.cscs.yml'

stages:
  - deps
  - build
  - test
  - deploy

variables:
  jfrogtag: 'docker_jfrog'

# default:
#     tags: ['dom']

# {{{ ubuntu:gnu:
# {{{ ubu:deps
ubu:deps:
  stage: deps
  extends: .deps-ubu-gnu_fake
  image: debian:testing-slim
  tags: 
    - $jfrogtag
  script:
    - echo "empty stage for a better display of deps"
  variables:
    PERSIST_IMAGE_NAME: debian:testing-slim
#ok {{{ # uncomment to rebuild the base image
#ok ubu:deps:
#ok   stage: deps
#ok   extends: .deps-ubu-gnu
#ok   image: nvidia/cuda:11.4.2-devel-ubuntu20.04
#ok   tags:
#ok     - $jfrogtag
#ok   script:
#ok     - which cmake
#ok   variables:
#ok     PERSIST_IMAGE_NAME: sph-exa_base:1.0
# TODO: build image if true/false
# }}}
# }}}

# {{{ build:ubu:gnu:
build:ubu:gnu:
  stage: build
  extends: .build
  image: art.cscs.ch/contbuild/testing/anfink/sph-exa_base:1.0
  tags:
    - $jfrogtag
  needs: ['ubu:deps']
  script:
    - ls -l /usr/local/sbin/
  variables:
    PERSIST_IMAGE_NAME: sph-exa_gnu:1.0
    # FIXME: should not be a static version (should be the SHA hash
    # ($CI_COMMIT_SHA) instead of 1.0) but this will fill up JFrog, so we would
    # need a deletion policy (todo) and/or a deploy step to retag (todo) the
    # container with a usable version.
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
# }}}

# {{{ test:ubu:
ubu:test_1:
  stage: test
  extends: .run-1
  image: art.cscs.ch/contbuild/testing/anfink/sph-exa_gnu:1.0
  # tags: ['dom']
  needs: ['build:ubu:gnu']
  script:
    - echo
  variables:
    PULL_IMAGE: 'YES'
    CSCS_REGISTRY_LOGIN: 'YES'
    SLURM_PARTITION: cscsci
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_CONSTRAINT: 'gpu'
    USE_MPI: 'YES'
    # SLURM_TIMELIMIT=15:00
    # PERSIST_IMAGE_NAME: sph-exa_gnu_tested:1.0

ubu:test_2:
  stage: test
  extends: .run-2
  image: art.cscs.ch/contbuild/testing/anfink/sph-exa_gnu:1.0
  # tags: ['dom']
  needs: ['build:ubu:gnu']
  script:
    - echo
  variables:
    PULL_IMAGE: 'YES'
    CSCS_REGISTRY_LOGIN: 'YES'
    SLURM_PARTITION: cscsci
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 2
    SLURM_CONSTRAINT: 'gpu'
    USE_MPI: 'YES'
    # SLURM_TIMELIMIT=15:00
    # PERSIST_IMAGE_NAME: sph-exa_gnu_tested:1.0

ubu:test_10:
  stage: test
  extends: .run-10
  image: art.cscs.ch/contbuild/testing/anfink/sph-exa_gnu:1.0
  # tags: ['dom']
  needs: ['build:ubu:gnu']
  script:
    - echo
  variables:
    PULL_IMAGE: 'YES'
    CSCS_REGISTRY_LOGIN: 'YES'
    SLURM_PARTITION: cscsci
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 10
    SLURM_CONSTRAINT: 'gpu'
    USE_MPI: 'YES'
    # SLURM_TIMELIMIT=15:00
    # PERSIST_IMAGE_NAME: sph-exa_gnu_tested:1.0

ubu:test_p100:
  stage: test
  extends: .run-p100
  image: art.cscs.ch/contbuild/testing/anfink/sph-exa_gnu:1.0
  # tags: ['dom']
  needs: ['build:ubu:gnu']
  script:
    - echo
  variables:
    PULL_IMAGE: 'YES'
    CSCS_REGISTRY_LOGIN: 'YES'
    SLURM_PARTITION: cscsci
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_CONSTRAINT: 'gpu'
    USE_MPI: 'YES'
    # SLURM_TIMELIMIT=15:00
    # PERSIST_IMAGE_NAME: sph-exa_gnu_tested:1.0
# }}}

# TODO: ubu:deploy:
#   stage: deploy
#   needs: ['ubu:test_1', 'ubu:test_2', 'ubu:test_12', 'ubu:test_p100']
#   script: echo
# }}}

# {{{ cpe_gnu: see commit ab188771
# }}}
