#!/bin/bash

# ----------------------------------------------------------------
# simple pre commit hook script to check that *.cpp and *.hpp files
# are correctly clang-formatted and that CMakeLists.txt 

# To use this hook, you must have clang-format installed

# To install this hook, copy this file to your git hooks as follows
# cp scripts/pre-commit .git/hooks/pre-commit
# chmod +x .git/hooks/pre-commit

red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
normal=$(tput sgr0)

since_commit=$1

cxxfiles=()
for file in `git diff --cached --name-only --diff-filter=ACMRT ${since_commit} | grep -E "\.(cpp|hpp|h)$"`; do
    if ! cmp -s <(git show :${file}) <(git show :${file}|clang-format -style=file); then
        cxxfiles+=("${file}")
    fi
done

returncode=0
full_list=

if [ -n "${cxxfiles}" ]; then
    printf "# ${blue}clang-format ${red}error pre-commit${normal} : To fix run the following (use git commit ${yellow}--no-verify${normal} to bypass)\n"
    for f in "${cxxfiles[@]}" ; do
        rel=$(realpath --relative-to "./$GIT_PREFIX" $f)
        printf "clang-format -i %s\n" "$rel"
        full_list="${rel} ${full_list}"
    done
    returncode=1
fi

if [ ! -z "$full_list" ]; then
    printf "\n# ${red}To commit the corrected files, run\n${normal}\ngit add ${full_list}\n"
fi

exit $returncode
